# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Asheville Website Developer | Drupal, WordPress, SEO
email: doostinharrell@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Dustin Harrell is a web developer located Asheville, NC Website specializing in Drupal
  website development, theming, and module development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dustinharrell.com" # the base hostname & protocol for your site
twitter_username: doostinharrell
github_username:  doostinharrell

# Build settings
markdown: kramdown

# Where things are
source:       ./src/html
destination:  ./dist/html
plugins_dir:  ./_plugins
layouts_dir:  ./_layouts
data_dir:     ./_data
includes_dir: ./_includes
collections:  null
